import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter, Work_Sans as WorkSans } from 'next/font/google'

import ToastProvider from '@/contexts/ToastContext'
import Providers from '@/contexts/ReduxContext'

// Styles
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const workSans = WorkSans({
  subsets: ['latin'],
  variable: '--font-work-sans',
})

export const metadata: Metadata = {
  title: 'PulseConnect',
  description: 'Generated by create next app',
}

const fontVariables = [inter.variable, workSans.variable].join(' ')

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
		
    <Providers>
      <html lang="pt-br" className={`${fontVariables}`}>
        <body>
          {children}
          <ToastProvider />
        </body>
      </html>
    </Providers>
  )
}
