import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";

// Styles
import "./globals.css";
import ToastProvider from "@/contexts/ToastContext";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "PulseConnect",
  description: "Generated by create next app",
};

const fontVariables = [inter.variable, workSans.variable].join(" ");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={fontVariables}>
      <body>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
