version: "1.0"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  db-migrations:
    build:
      context: .
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    command: npm run db:migrate
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/home/node/api/src
    container_name: "pulseconnect"
    depends_on:
      - db
      - db-migrations
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev
volumes:
  pgdata: {}
  nodemodules: {}