# fly.toml app configuration file generated for pulseconnect on 2023-09-09T21:54:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pulseconnect"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
